language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - yarn
before_script:
  - yarn lint
  - yarn lint:test
  - yarn lint:test:e2e
  - yarn test:coverage
script:
  - yarn dist
after_success:
  - yarn coveralls
  - TRAVIS=travis yarn test:e2e
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  local_dir: dist
  on:
    branch: master
