language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
branches:
  only:
    - master
cache:
  yarn: true
install:
  - yarn
before_script:
  - yarn lint
  - yarn lint:test
  - yarn lint:test:e2e
  - yarn test:coverage
script:
  - yarn dist
after_success:
  - yarn coveralls
  - TRAVIS=travis yarn test:e2e
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  allow_empty_commit: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
